"""
seed_data.py
------------
Define la taxonomía de categorías, subcategorías y tags predefinidos
sobre Spring Boot, Data & Persistencia e Inteligencia Artificial.

La constante TAXONOMY puede usarse como entrada por defecto para la
generación de artículos.
"""

# ─── taxonomía de temas ───────────────────────────────────────────────────────
# Estructura:  { "name": str, "description": str, "subcategories": [ { "name", "description", "tags": [str, ...] } ] }

TAXONOMY = [
    {
        "name": "Spring Boot",
        "description": "Desarrollo de aplicaciones Java con el framework Spring Boot.",
        "subcategories": [
            {
                "name": "Spring Boot Core",
                "description": "Fundamentos y configuración automática de Spring Boot.",
                "tags": [
                    "@SpringBootApplication",
                    "Auto-configuration",
                    "Spring Profiles",
                    "application.yml",
                    "application.properties",
                    "CommandLineRunner",
                    "@ConditionalOnProperty",
                    "Embedded Tomcat",
                    "Spring Boot Actuator",
                    "Spring Boot DevTools",
                ],
            },
            {
                "name": "Spring Security",
                "description": "Autenticación y autorización con Spring Security.",
                "tags": [
                    "JWT Authentication",
                    "OAuth2 y OpenID Connect",
                    "Spring Security Filter Chain",
                    "@PreAuthorize",
                    "@Secured",
                    "CORS Configuration",
                    "CSRF Protection",
                    "UserDetailsService",
                    "BCryptPasswordEncoder",
                    "Method Security",
                ],
            },
            {
                "name": "Spring Data JPA",
                "description": "Persistencia de datos con Spring Data JPA e Hibernate.",
                "tags": [
                    "@Entity y @Table",
                    "JpaRepository",
                    "@Query personalizada",
                    "@Transactional",
                    "@OneToMany y @ManyToOne",
                    "Paginación con Pageable",
                    "Criteria API",
                    "Projections y DTOs",
                    "@ManyToMany",
                    "Spring Data Specifications",
                ],
            },
            {
                "name": "Spring MVC REST",
                "description": "Creación de APIs REST con Spring MVC.",
                "tags": [
                    "@RestController",
                    "@GetMapping y @PostMapping",
                    "@RequestBody y @ResponseBody",
                    "@PathVariable y @RequestParam",
                    "ResponseEntity",
                    "@ControllerAdvice",
                    "@Valid y Bean Validation",
                    "HATEOAS",
                    "OpenAPI y Swagger",
                    "Content Negotiation",
                ],
            },
            {
                "name": "Spring Boot Testing",
                "description": "Pruebas de integración y unitarias en Spring Boot.",
                "tags": [
                    "@SpringBootTest",
                    "@WebMvcTest",
                    "@DataJpaTest",
                    "@MockBean y Mockito",
                    "Testcontainers",
                    "@ParameterizedTest",
                    "MockMvc",
                    "WireMock",
                    "@TestConfiguration",
                    "JUnit 5 con Spring",
                ],
            },
            {
                "name": "Lombok",
                "description": "Reducción de código boilerplate Java con Lombok.",
                "tags": [
                    "@Data",
                    "@Builder",
                    "@NoArgsConstructor y @AllArgsConstructor",
                    "@Getter y @Setter",
                    "@Slf4j",
                    "@Value",
                    "@RequiredArgsConstructor",
                    "@EqualsAndHashCode",
                    "@ToString",
                    "@SuperBuilder",
                ],
            },
        ],
    },
    {
        "name": "Data & Persistencia",
        "description": "Gestión y persistencia de datos en aplicaciones Java.",
        "subcategories": [
            {
                "name": "JPA e Hibernate",
                "description": "Mapeo objeto-relacional con JPA e Hibernate.",
                "tags": [
                    "Hibernate Caching L1 y L2",
                    "Problema N+1 y soluciones",
                    "FetchType LAZY vs EAGER",
                    "Inheritance Strategies",
                    "Native Queries",
                    "HQL (Hibernate Query Language)",
                    "@Embeddable y @Embedded",
                    "@MappedSuperclass",
                    "Hibernate Envers (auditoría)",
                    "Connection Pooling HikariCP",
                ],
            },
            {
                "name": "Bases de Datos SQL",
                "description": "Integración de Spring Boot con bases de datos relacionales.",
                "tags": [
                    "PostgreSQL con Spring Boot",
                    "MySQL con Spring Boot",
                    "H2 Database (testing)",
                    "Índices y optimización SQL",
                    "Stored Procedures con JPA",
                    "Spring JDBC Template",
                    "Transacciones distribuidas",
                    "Multi-datasource en Spring Boot",
                    "QueryDSL",
                    "jOOQ con Spring Boot",
                ],
            },
            {
                "name": "NoSQL y MongoDB",
                "description": "Bases de datos NoSQL con Spring Boot.",
                "tags": [
                    "Spring Data MongoDB",
                    "@Document y @Field",
                    "MongoRepository",
                    "Aggregation Pipeline con Spring",
                    "Spring Data Redis",
                    "Caché con Redis y Spring",
                    "Spring Data Elasticsearch",
                    "Cassandra con Spring Boot",
                    "@DBRef en MongoDB",
                    "GridFS con Spring",
                ],
            },
            {
                "name": "Migraciones de Esquema",
                "description": "Versionado y migración de esquemas de base de datos.",
                "tags": [
                    "Flyway con Spring Boot",
                    "Liquibase con Spring Boot",
                    "Versionado de migraciones SQL",
                    "Rollback con Flyway",
                    "Baseline en Flyway",
                    "Checksum en Liquibase",
                    "Migraciones en entornos CI/CD",
                    "Flyway Callbacks",
                ],
            },
        ],
    },
    {
        "name": "Inteligencia Artificial",
        "description": "Integración de IA y Machine Learning con Java y Spring.",
        "subcategories": [
            {
                "name": "Spring AI",
                "description": "Integración nativa de modelos de IA con Spring AI.",
                "tags": [
                    "Spring AI Overview",
                    "ChatClient con Spring AI",
                    "Prompt Templates en Spring AI",
                    "Function Calling con Spring AI",
                    "Spring AI y Ollama",
                    "Spring AI Advisors",
                    "Spring AI con OpenAI",
                    "Spring AI con Azure OpenAI",
                    "Spring AI con Mistral",
                    "Multimodalidad en Spring AI",
                ],
            },
            {
                "name": "LLMs y Modelos de Lenguaje",
                "description": "Uso de grandes modelos de lenguaje (LLMs) en aplicaciones Java.",
                "tags": [
                    "OpenAI API con Java",
                    "GPT-4 y modelos avanzados",
                    "Tokens y Context Window",
                    "Streaming de respuestas LLM",
                    "Fine-tuning de modelos",
                    "Prompt Engineering avanzado",
                    "Chain of Thought (CoT)",
                    "Few-shot Learning",
                    "LangChain4j",
                    "Integración con Hugging Face",
                ],
            },
            {
                "name": "Machine Learning con Java",
                "description": "Algoritmos y frameworks de ML para aplicaciones Java.",
                "tags": [
                    "Deeplearning4j",
                    "Weka con Java",
                    "ONNX Runtime en Java",
                    "TensorFlow Java",
                    "Tribuo (Oracle ML)",
                    "Clasificación con Smile",
                    "Regresión lineal en Java",
                    "Árboles de decisión en Java",
                    "Cross-validation en Java",
                    "Pipeline de datos ML en Java",
                ],
            },
            {
                "name": "Vector Databases y RAG",
                "description": "Búsqueda semántica, embeddings y generación aumentada por recuperación (RAG).",
                "tags": [
                    "Embeddings con Spring AI",
                    "Pinecone con Java",
                    "Qdrant con Spring AI",
                    "RAG (Retrieval Augmented Generation)",
                    "Chroma DB con Spring",
                    "Búsqueda semántica",
                    "VectorStore en Spring AI",
                    "pgvector con Spring Boot",
                    "Weaviate con Spring",
                    "Milvus con Java",
                ],
            },
        ],
    },
]

