package io.github.aigen.pregunta.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * JPA entity that maps to the {@code preguntas} table in PostgreSQL.
 *
 * <p>The table schema is:
 * <pre>{@code
 * CREATE TABLE preguntas (
 *     id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 *     campo         VARCHAR(255) NOT NULL,
 *     orden         INTEGER      NOT NULL,
 *     texto         JSONB        NOT NULL,
 *     actualizada_en TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 * }</pre>
 *
 * <p>The {@code texto} column is a JSONB object with one entry per supported locale:
 * {@code ca} (Catalan), {@code en} (English), {@code es} (Spanish), {@code fr} (French).
 *
 * <p>Example row:
 * <pre>{@code
 * {
 *   "id":     "63838a84-01e6-4fab-ac9b-3906a92fc29d",
 *   "campo":  "viviendaAlquiler",
 *   "orden":  1,
 *   "texto":  { "ca": "Vius de lloguer?", "en": "Do you live in a rented home?",
 *               "es": "¿Vives de alquiler?", "fr": "Vivez-vous en location?" },
 *   "actualizada_en": "2026-04-27T22:42:43.572793+00:00"
 * }
 * }</pre>
 */
@Entity
@Table(name = "preguntas")
public class Pregunta {

    /** UUID primary key — generated by the database via {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /** Camel-case programmatic identifier for the question (e.g. {@code viviendaAlquiler}). */
    @Column(nullable = false, length = 255)
    private String campo;

    /** Display order in the questionnaire (1-based). */
    @Column(nullable = false)
    private Integer orden;

    /**
     * Multilingual question text stored as JSONB.
     * Keys are ISO 639-1 language codes: {@code ca}, {@code en}, {@code es}, {@code fr}.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private Map<String, String> texto;

    /** Timestamp of the last update (with time zone). */
    @Column(name = "actualizada_en", nullable = false)
    private OffsetDateTime actualizadaEn;

    // ── Constructors ──────────────────────────────────────────────────────

    public Pregunta() {}

    public Pregunta(String campo, Integer orden, Map<String, String> texto) {
        this.campo        = campo;
        this.orden        = orden;
        this.texto        = texto;
        this.actualizadaEn = OffsetDateTime.now();
    }

    // ── Getters & Setters ─────────────────────────────────────────────────

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public String getCampo() { return campo; }
    public void setCampo(String campo) { this.campo = campo; }

    public Integer getOrden() { return orden; }
    public void setOrden(Integer orden) { this.orden = orden; }

    public Map<String, String> getTexto() { return texto; }
    public void setTexto(Map<String, String> texto) { this.texto = texto; }

    public OffsetDateTime getActualizadaEn() { return actualizadaEn; }
    public void setActualizadaEn(OffsetDateTime actualizadaEn) { this.actualizadaEn = actualizadaEn; }

    @Override
    public String toString() {
        String es = texto != null ? texto.get("es") : null;
        return "Pregunta{id=" + id + ", campo='" + campo + "', orden=" + orden
                + ", texto_es='" + es + "'}";
    }
}
